version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install -U pip
      - pip install sphinx furo myst-parser sphinx-copybutton sphinx-design sphinxcontrib-video sphinxext-opengraph linkify-it-py

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
