version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install -U pip

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
